language: python
python: 3.6

env:
  global:
  - ENCRYPTION_LABEL: "defac9b1fa56"
  - COMMIT_AUTHOR_EMAIL: "nobody@coala.io"

before_install:
  - echo coala-bears >> requirements.txt
  - npm i -g jshint

script:
  - ./.ci/build.sh
  - coala --non-interactive -V

after_success:
  - ./.ci/deploy.sh
